
TRAIN_IMAGES_PATH = 'data/dogs-vs-cats/train'
TEST_IMAGES_PATH = 'data/dogs-vs-cats/test1'

IMAGE_LABEL = "image"
CLASS_LABEL = "class"
DOG_LABEL = "dog"
CAT_LABEL = "cat"

VALID_SIZE = 0.2

BATCH_SIZE = 32

IMG_WIDTH=128
IMG_HEIGHT=128
IMG_CHANNELS=3
IMG_SIZE=(IMG_WIDTH, IMG_HEIGHT)
LEARNING_RATE=0.001

KERNEL_SIZE_CONV = 3
KERNEL_SIZE = (KERNEL_SIZE_CONV, KERNEL_SIZE_CONV)
POOL_SIZE = 2
PADDING = 1
MAXPOOL_STRIDE = 2
RELU_ACTIVATION = 'relu'
EPOCHS = 10
